workflows:
  ios-testflight:
    name: RBM Holdings iOS TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.rbmbusinessholdingsinc.app"
      flutter: stable
      xcode: latest
      cocoapods: default
    integrations:
      app_store_connect: "RBM Connect"
    scripts:
      - name: Initialize Keychain
        script: keychain initialize
      - name: Fetch Signing Files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add Certificates
        script: keychain add-certificates
      - name: Use Profiles
        script: xcode-project use-profiles
      - name: Build and Sign IPA
        script: |
          flutter pub get
          flutter build ipa --release --export-options-plist=$CM_EXPORT_OPTIONS_PATH --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Testers"
