# The next line is added by the Flutter tool
# and it is required to locate the Flutter SDK and its tools.
# It is important not to delete or modify this line.
# If you are using a custom Flutter installation, you may need to adjust the path.
load File.join(File.dirname(File.realpath(__FILE__)), '..', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
